// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Actiontarget
    {
        public int Actiontargetid { get; set; }
        public int? Actionid { get; set; }
        public Guid? Roleid { get; set; }
        public int? Targetid { get; set; }
        public string Projectid { get; set; }

        public virtual Actions Action { get; set; }
        public virtual Target Target { get; set; }
    }
}