// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Actiontype
    {
        public Actiontype()
        {
            Actions = new HashSet<Actions>();
        }

        public int Actiontypeid { get; set; }
        public string Name { get; set; }
        public string Projectid { get; set; }

        public virtual ICollection<Actions> Actions { get; set; }
    }
}