// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Actions
    {
        public Actions()
        {
            Actiontarget = new HashSet<Actiontarget>();
            Requestaction = new HashSet<Requestaction>();
            Transitionaction = new HashSet<Transitionaction>();
        }

        public int Actionid { get; set; }
        public int Actiontypeid { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int Processid { get; set; }
        public string Projectid { get; set; }

        public virtual Actiontype Actiontype { get; set; }
        public virtual ICollection<Actiontarget> Actiontarget { get; set; }
        public virtual ICollection<Requestaction> Requestaction { get; set; }
        public virtual ICollection<Transitionaction> Transitionaction { get; set; }
    }
}