// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Activitytarget
    {
        public int Activitytargetid { get; set; }
        public int? Activityid { get; set; }
        public Guid? Roleid { get; set; }
        public int? Targetid { get; set; }
        public string Projectid { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual Target Target { get; set; }
    }
}