// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class AspNetUserGroup
    {
        public string GroupId { get; set; }
        public string UserId { get; set; }

        public virtual AspNetGroups Group { get; set; }
        public virtual AspNetUsers User { get; set; }
    }
}