// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class AspNetGroups
    {
        public AspNetGroups()
        {
            AspNetRoleGroup = new HashSet<AspNetRoleGroup>();
            AspNetUserGroup = new HashSet<AspNetUserGroup>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<AspNetRoleGroup> AspNetRoleGroup { get; set; }
        public virtual ICollection<AspNetUserGroup> AspNetUserGroup { get; set; }
    }
}