// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class AspNetRoles
    {
        public AspNetRoles()
        {
            AspNetRoleGroup = new HashSet<AspNetRoleGroup>();
            AspNetUserRoles = new HashSet<AspNetUserRoles>();
            BudgetRole = new HashSet<BudgetRole>();
            JenisRole = new HashSet<JenisRole>();
            OrderItem = new HashSet<OrderItem>();
            OrderReload = new HashSet<OrderReload>();
            OrderRequest = new HashSet<OrderRequest>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string NormalizedName { get; set; }
        public string ConcurrencyStamp { get; set; }

        public virtual ICollection<AspNetRoleGroup> AspNetRoleGroup { get; set; }
        public virtual ICollection<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual ICollection<BudgetRole> BudgetRole { get; set; }
        public virtual ICollection<JenisRole> JenisRole { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual ICollection<OrderReload> OrderReload { get; set; }
        public virtual ICollection<OrderRequest> OrderRequest { get; set; }
    }
}