// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class AssetRequests
    {
        public AssetRequests()
        {
            AssetRequestDetails = new HashSet<AssetRequestDetails>();
        }

        public int Id { get; set; }
        public string RequestNo { get; set; }
        public int RequesterId { get; set; }
        public int? OfficeRoomId { get; set; }
        public int? DepartementId { get; set; }
        public int? AssetConditionId { get; set; }
        public int? AssetId { get; set; }
        public string Status { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime? RequestChangeAt { get; set; }
        public int TypeId { get; set; }
        public DateTime RequestDate { get; set; }
        public int? RequestId { get; set; }
        public int? RegionalId { get; set; }
        public bool Depreciated { get; set; }

        public virtual Assets Asset { get; set; }
        public virtual Jenis AssetCondition { get; set; }
        public virtual OfficeRooms OfficeRoom { get; set; }
        public virtual OfficeLocationRegions Regional { get; set; }
        public virtual RequestFlow Request { get; set; }
        public virtual Users Requester { get; set; }
        public virtual AssetTypes Type { get; set; }
        public virtual ICollection<AssetRequestDetails> AssetRequestDetails { get; set; }
    }
}