// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Assets
    {
        public Assets()
        {
            AssetBorrow = new HashSet<AssetBorrow>();
            AssetRequests = new HashSet<AssetRequests>();
            BorrowRequests = new HashSet<BorrowRequests>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int YearAcquired { get; set; }
        public decimal PriceAcquired { get; set; }
        public string SerialNumber { get; set; }
        public bool? CanBorrow { get; set; }
        public string AssetNumber { get; set; }
        public int RunningNumber { get; set; }
        public int? VendorId { get; set; }
        public string Description { get; set; }
        public DateTime? DeletedAt { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string Barcode { get; set; }
        public int? BrandSeriesId { get; set; }
        public int? GroupId { get; set; }
        public int? AssetOwnerId { get; set; }

        public virtual Jenis AssetOwner { get; set; }
        public virtual AssetBrandSeries BrandSeries { get; set; }
        public virtual AssetSubGroupTypes Group { get; set; }
        public virtual ICollection<AssetBorrow> AssetBorrow { get; set; }
        public virtual ICollection<AssetRequests> AssetRequests { get; set; }
        public virtual ICollection<BorrowRequests> BorrowRequests { get; set; }
    }
}