// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class BorrowRequestDetails
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public int ActorId { get; set; }
        public string Comments { get; set; }
        public string FilePath { get; set; }
        public string Status { get; set; }
        public string Action { get; set; }
        public string State { get; set; }
        public DateTime? DeletedAt { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual Users Actor { get; set; }
        public virtual BorrowRequests Request { get; set; }
    }
}