// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Budget
    {
        public Budget()
        {
            BudgetRole = new HashSet<BudgetRole>();
            MeetingRequestBudgets = new HashSet<MeetingRequestBudgets>();
            OrderItem = new HashSet<OrderItem>();
            TravelHotel = new HashSet<TravelHotel>();
            TravelTransportationName = new HashSet<TravelTransportationName>();
        }

        public int BudgetId { get; set; }
        public string BudgetName { get; set; }
        public string BudgetDesc { get; set; }
        public decimal? BudgetNominal { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<BudgetRole> BudgetRole { get; set; }
        public virtual ICollection<MeetingRequestBudgets> MeetingRequestBudgets { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual ICollection<TravelHotel> TravelHotel { get; set; }
        public virtual ICollection<TravelTransportationName> TravelTransportationName { get; set; }
    }
}