// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class CarBudgetDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal? Nominal { get; set; }
        public int? BudgetId { get; set; }
        public string FileLocation { get; set; }
        public bool Done { get; set; }
        public int CarRequestBudgetId { get; set; }
        public int? CarRequestDetailStatusId { get; set; }

        public virtual Jenis Budget { get; set; }
        public virtual CarRequestBudget CarRequestBudget { get; set; }
        public virtual CarBudgetDetailStatus CarRequestDetailStatus { get; set; }
    }
}