// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class CarBudgetDetailStatus
    {
        public CarBudgetDetailStatus()
        {
            CarBudgetDetail = new HashSet<CarBudgetDetail>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int StatusValue { get; set; }

        public virtual ICollection<CarBudgetDetail> CarBudgetDetail { get; set; }
    }
}