// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class CarRequests
    {
        public CarRequests()
        {
            CarRequestCoordinate = new HashSet<CarRequestCoordinate>();
        }

        public int Id { get; set; }
        public int RequesterId { get; set; }
        public int CarPoolId { get; set; }
        public DateTime RequiredAt { get; set; }
        public string Description { get; set; }
        public string Destination { get; set; }
        public string Status { get; set; }
        public bool? Done { get; set; }
        public DateTime? DeletedAt { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public int? RegionalId { get; set; }
        public string CarRequestNo { get; set; }
        public int? RequestId { get; set; }
        public bool? UsingDriver { get; set; }
        public decimal TotalBudget { get; set; }
        public int? StatusAnggaranId { get; set; }
        public decimal FundAvailable { get; set; }
        public string NoAccount { get; set; }
        public decimal BudgetLeft { get; set; }

        public virtual CarPools CarPool { get; set; }
        public virtual OfficeLocationRegions Regional { get; set; }
        public virtual RequestFlow Request { get; set; }
        public virtual Users Requester { get; set; }
        public virtual CarRequestBudget CarRequestBudget { get; set; }
        public virtual ICollection<CarRequestCoordinate> CarRequestCoordinate { get; set; }
    }
}