// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class CarRequestCoordinate
    {
        public CarRequestCoordinate()
        {
            CarRequestCoordinateDetail = new HashSet<CarRequestCoordinateDetail>();
        }

        public long Id { get; set; }
        public int CarRequestId { get; set; }
        public int CarCoordinateStatusId { get; set; }
        public DateTime CurrentDateTime { get; set; }

        public virtual CarRequestCoordinateStatus CarCoordinateStatus { get; set; }
        public virtual CarRequests CarRequest { get; set; }
        public virtual ICollection<CarRequestCoordinateDetail> CarRequestCoordinateDetail { get; set; }
    }
}