// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class CarRequestCoordinateDetail
    {
        public long Id { get; set; }
        public long CarRequestCoordinateId { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public DateTime TransactionDateTime { get; set; }

        public virtual CarRequestCoordinate CarRequestCoordinate { get; set; }
    }
}