// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class CarRequestBudget
    {
        public CarRequestBudget()
        {
            CarBudgetDetail = new HashSet<CarBudgetDetail>();
        }

        public int CarRequestId { get; set; }
        public DateTime? TransactionDate { get; set; }
        public DateTime? RequestStart { get; set; }
        public DateTime? RequestEnd { get; set; }
        public string CarRequestBudgetNo { get; set; }
        public int? RequesterId { get; set; }
        public string Description { get; set; }
        public int? DriverId { get; set; }
        public bool Checked { get; set; }
        public int? RequestId { get; set; }
        public string Type { get; set; }
        public decimal? Balance { get; set; }

        public virtual CarRequests CarRequest { get; set; }
        public virtual CarDrivers Driver { get; set; }
        public virtual RequestFlow Request { get; set; }
        public virtual Users Requester { get; set; }
        public virtual ICollection<CarBudgetDetail> CarBudgetDetail { get; set; }
    }
}