// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class ChangeLog
    {
        public int ChangeLogId { get; set; }
        public string Title { get; set; }
        public int? UserId { get; set; }
        public string Description { get; set; }
        public DateTime? ChangeLogDate { get; set; }

        public virtual Users User { get; set; }
    }
}