// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Jabatan
    {
        public Jabatan()
        {
            AssetBorrow = new HashSet<AssetBorrow>();
            JabatanChildJabatanChildNavigation = new HashSet<JabatanChild>();
            JabatanChildParentJabatan = new HashSet<JabatanChild>();
            OrderReload = new HashSet<OrderReload>();
            OrderRequest = new HashSet<OrderRequest>();
            RepairItemRequests = new HashSet<RepairItemRequests>();
            TravelRequest = new HashSet<TravelRequest>();
            Users = new HashSet<Users>();
        }

        public int JabatanId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<AssetBorrow> AssetBorrow { get; set; }
        public virtual ICollection<JabatanChild> JabatanChildJabatanChildNavigation { get; set; }
        public virtual ICollection<JabatanChild> JabatanChildParentJabatan { get; set; }
        public virtual ICollection<OrderReload> OrderReload { get; set; }
        public virtual ICollection<OrderRequest> OrderRequest { get; set; }
        public virtual ICollection<RepairItemRequests> RepairItemRequests { get; set; }
        public virtual ICollection<TravelRequest> TravelRequest { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}