// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class JenisRole
    {
        public int JenisRoleId { get; set; }
        public int? JenisId { get; set; }
        public string RoleId { get; set; }

        public virtual Jenis Jenis { get; set; }
        public virtual AspNetRoles Role { get; set; }
    }
}