// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class MeetingRooms
    {
        public MeetingRooms()
        {
            MeetingRequestFlow = new HashSet<MeetingRequestFlow>();
            MeetingRequests = new HashSet<MeetingRequests>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? RoomId { get; set; }
        public int PicId { get; set; }
        public int? RoomCategoryId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public bool Active { get; set; }

        public virtual Users Pic { get; set; }
        public virtual OfficeRooms Room { get; set; }
        public virtual MeetingRoomsCategory RoomCategory { get; set; }
        public virtual ICollection<MeetingRequestFlow> MeetingRequestFlow { get; set; }
        public virtual ICollection<MeetingRequests> MeetingRequests { get; set; }
    }
}