// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class MeetingRequestFlow
    {
        public int Id { get; set; }
        public int? MeetingRequestId { get; set; }
        public int? RequestId { get; set; }
        public int? MeetingRoomId { get; set; }

        public virtual MeetingRequests MeetingRequest { get; set; }
        public virtual MeetingRooms MeetingRoom { get; set; }
        public virtual RequestFlow Request { get; set; }
    }
}