// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class MeetingRequestTime
    {
        public int Id { get; set; }
        public int? MeetingRequestId { get; set; }
        public int? Sequence { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }

        public virtual MeetingRequests MeetingRequest { get; set; }
    }
}