// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class MeetingRequests
    {
        public MeetingRequests()
        {
            MeetingRequestAccountability = new HashSet<MeetingRequestAccountability>();
            MeetingRequestBudgets = new HashSet<MeetingRequestBudgets>();
            MeetingRequestFlow = new HashSet<MeetingRequestFlow>();
            MeetingRequestTime = new HashSet<MeetingRequestTime>();
        }

        public int Id { get; set; }
        public int RequesterId { get; set; }
        public int MeetingRoomId { get; set; }
        public int MeetingTypeId { get; set; }
        public int NumOfParticipant { get; set; }
        public int? BudgetsId { get; set; }
        public string Status { get; set; }
        public DateTime? DeletedAt { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public decimal? FundAvailable { get; set; }
        public int? DepartmentId { get; set; }
        public string MeetingRequestNo { get; set; }
        public string MeetingTitle { get; set; }
        public string MeetingDesc { get; set; }
        public bool Approved { get; set; }
        public int? StatusAnggaranId { get; set; }
        public decimal? TotalBudgetBook { get; set; }
        public int? PicId { get; set; }
        public string NoAkun { get; set; }
        public string BudgetLeft { get; set; }

        public virtual MeetingRooms MeetingRoom { get; set; }
        public virtual Jenis MeetingType { get; set; }
        public virtual Users Requester { get; set; }
        public virtual ICollection<MeetingRequestAccountability> MeetingRequestAccountability { get; set; }
        public virtual ICollection<MeetingRequestBudgets> MeetingRequestBudgets { get; set; }
        public virtual ICollection<MeetingRequestFlow> MeetingRequestFlow { get; set; }
        public virtual ICollection<MeetingRequestTime> MeetingRequestTime { get; set; }
    }
}