// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class MeetingRequestAccountabilityFlow
    {
        public int Id { get; set; }
        public int? MeetingRequestAccountabilityId { get; set; }
        public int? RequestId { get; set; }
        public int? RegionalId { get; set; }

        public virtual MeetingRequestAccountability MeetingRequestAccountability { get; set; }
        public virtual OfficeLocationRegions Regional { get; set; }
        public virtual RequestFlow Request { get; set; }
    }
}