// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class MeetingRequestAccountability
    {
        public MeetingRequestAccountability()
        {
            MeetingRequestAccountabilityFiles = new HashSet<MeetingRequestAccountabilityFiles>();
            MeetingRequestAccountabilityFlow = new HashSet<MeetingRequestAccountabilityFlow>();
        }

        public int Id { get; set; }
        public int? MeetingRequestId { get; set; }
        public int? PicId { get; set; }
        public decimal? TotalBudgetReal { get; set; }
        public int? NumOfPartisipant { get; set; }
        public string Status { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual MeetingRequests MeetingRequest { get; set; }
        public virtual Users Pic { get; set; }
        public virtual ICollection<MeetingRequestAccountabilityFiles> MeetingRequestAccountabilityFiles { get; set; }
        public virtual ICollection<MeetingRequestAccountabilityFlow> MeetingRequestAccountabilityFlow { get; set; }
    }
}