// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class MeetingRoomsCategory
    {
        public MeetingRoomsCategory()
        {
            MeetingRooms = new HashSet<MeetingRooms>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? MinPerson { get; set; }
        public int? MaxPerson { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<MeetingRooms> MeetingRooms { get; set; }
    }
}