// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class MeetingRequestBudgets
    {
        public int Id { get; set; }
        public int? MeetingRequestId { get; set; }
        public decimal Amount { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public bool Active { get; set; }
        public int? MeetingBudgetId { get; set; }
        public int QtyPerson { get; set; }
        public decimal TotalAmount { get; set; }
        public int QtyDays { get; set; }

        public virtual Budget MeetingBudget { get; set; }
        public virtual MeetingRequests MeetingRequest { get; set; }
    }
}