// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class OfficeLocations
    {
        public OfficeLocations()
        {
            CarDrivers = new HashSet<CarDrivers>();
            CarPools = new HashSet<CarPools>();
            OfficeRooms = new HashSet<OfficeRooms>();
            OrderReload = new HashSet<OrderReload>();
            OrderRequest = new HashSet<OrderRequest>();
            RepairItem = new HashSet<RepairItem>();
            RepairItemRequests = new HashSet<RepairItemRequests>();
            Stocks = new HashSet<Stocks>();
            TravelRequest = new HashSet<TravelRequest>();
            TravelRequestAccountability = new HashSet<TravelRequestAccountability>();
            Users = new HashSet<Users>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? LocationTypeId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public bool Active { get; set; }
        public int? RegionId { get; set; }

        public virtual OfficeLocationType LocationType { get; set; }
        public virtual OfficeLocationRegions Region { get; set; }
        public virtual ICollection<CarDrivers> CarDrivers { get; set; }
        public virtual ICollection<CarPools> CarPools { get; set; }
        public virtual ICollection<OfficeRooms> OfficeRooms { get; set; }
        public virtual ICollection<OrderReload> OrderReload { get; set; }
        public virtual ICollection<OrderRequest> OrderRequest { get; set; }
        public virtual ICollection<RepairItem> RepairItem { get; set; }
        public virtual ICollection<RepairItemRequests> RepairItemRequests { get; set; }
        public virtual ICollection<Stocks> Stocks { get; set; }
        public virtual ICollection<TravelRequest> TravelRequest { get; set; }
        public virtual ICollection<TravelRequestAccountability> TravelRequestAccountability { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}