// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class OfficeRooms
    {
        public OfficeRooms()
        {
            AssetBorrow = new HashSet<AssetBorrow>();
            AssetRequests = new HashSet<AssetRequests>();
            MeetingRooms = new HashSet<MeetingRooms>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int DepartmentId { get; set; }
        public int OfficeLocationId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public bool Active { get; set; }

        public virtual OfficeLocations OfficeLocation { get; set; }
        public virtual ICollection<AssetBorrow> AssetBorrow { get; set; }
        public virtual ICollection<AssetRequests> AssetRequests { get; set; }
        public virtual ICollection<MeetingRooms> MeetingRooms { get; set; }
    }
}