// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class OrderItemInventoryIt
    {
        public int OrderItemId { get; set; }
        public bool ItemIt { get; set; }

        public virtual OrderItem OrderItem { get; set; }
    }
}