// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class OrderRequestAccountabilityImage
    {
        public int Id { get; set; }
        public int ImageId { get; set; }
        public int OrderRequestId { get; set; }

        public virtual Image Image { get; set; }
        public virtual OrderRequestAccountability OrderRequest { get; set; }
    }
}