// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class OrderItem
    {
        public OrderItem()
        {
            OrderReloadDetail = new HashSet<OrderReloadDetail>();
            OrderRequestsDetail = new HashSet<OrderRequestsDetail>();
            Stocks = new HashSet<Stocks>();
        }

        public int Id { get; set; }
        public int JenisId { get; set; }
        public string SerialNumber { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Merk { get; set; }
        public bool Active { get; set; }
        public string RoleId { get; set; }
        public int BudgetId { get; set; }

        public virtual Budget Budget { get; set; }
        public virtual Jenis Jenis { get; set; }
        public virtual AspNetRoles Role { get; set; }
        public virtual OrderItemInventoryIt OrderItemInventoryIt { get; set; }
        public virtual OrderItemStock OrderItemStock { get; set; }
        public virtual ICollection<OrderReloadDetail> OrderReloadDetail { get; set; }
        public virtual ICollection<OrderRequestsDetail> OrderRequestsDetail { get; set; }
        public virtual ICollection<Stocks> Stocks { get; set; }
    }
}