// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class OrderItemStock
    {
        public int OrderItemId { get; set; }
        public int? MinStock { get; set; }
        public int? MaxStock { get; set; }
        public string Satuan1 { get; set; }
        public string Satuan2 { get; set; }
        public int? Konv1ke2 { get; set; }

        public virtual OrderItem OrderItem { get; set; }
    }
}