// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class OrderRequestImage
    {
        public int Id { get; set; }
        public int? OrderRequestId { get; set; }
        public int? ImageId { get; set; }

        public virtual Image Image { get; set; }
        public virtual OrderRequest OrderRequest { get; set; }
    }
}