// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class OrderReload
    {
        public OrderReload()
        {
            OrderReloadDetail = new HashSet<OrderReloadDetail>();
        }

        public int Id { get; set; }
        public string ReloadNo { get; set; }
        public string Description { get; set; }
        public int OfficeLocationId { get; set; }
        public int? RequesterId { get; set; }
        public DateTime? RequiredAt { get; set; }
        public DateTime? CreateAt { get; set; }
        public string RoleId { get; set; }
        public int? RequestId { get; set; }
        public int? JabatanId { get; set; }
        public decimal TotalBudget { get; set; }
        public int? StatusAnggaranId { get; set; }
        public decimal FundAvailable { get; set; }
        public string NoAccount { get; set; }
        public decimal BudgetLeft { get; set; }
        public int? BudgetId { get; set; }

        public virtual Jabatan Jabatan { get; set; }
        public virtual OfficeLocations OfficeLocation { get; set; }
        public virtual RequestFlow Request { get; set; }
        public virtual Users Requester { get; set; }
        public virtual AspNetRoles Role { get; set; }
        public virtual OrderReloadAccountability OrderReloadAccountability { get; set; }
        public virtual ICollection<OrderReloadDetail> OrderReloadDetail { get; set; }
    }
}