// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Process
    {
        public Process()
        {
            Activity = new HashSet<Activity>();
            Processadmin = new HashSet<Processadmin>();
            RequestFlow = new HashSet<RequestFlow>();
            State = new HashSet<State>();
            Transition = new HashSet<Transition>();
        }

        public int Processid { get; set; }
        public string Nama { get; set; }
        public string Projectid { get; set; }
        public string Url { get; set; }

        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<Processadmin> Processadmin { get; set; }
        public virtual ICollection<RequestFlow> RequestFlow { get; set; }
        public virtual ICollection<State> State { get; set; }
        public virtual ICollection<Transition> Transition { get; set; }
    }
}