// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Requestnote
    {
        public int Requestnoteid { get; set; }
        public string Note { get; set; }
        public int? Requestid { get; set; }
        public string Userid { get; set; }

        public virtual RequestFlow Request { get; set; }
    }
}