// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Requeststakeholder
    {
        public int Requestid { get; set; }
        public Guid Userid { get; set; }

        public virtual RequestFlow Request { get; set; }
    }
}