// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class RequestActionHistory
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public int RequestActionId { get; set; }
        public DateTime Datetime { get; set; }
        public string Note { get; set; }
        public int UserId { get; set; }
        public string HistoryType { get; set; }

        public virtual RequestFlow Request { get; set; }
        public virtual Requestaction RequestAction { get; set; }
        public virtual Users User { get; set; }
    }
}