// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class RequestFlow
    {
        public RequestFlow()
        {
            AssetBorrow = new HashSet<AssetBorrow>();
            AssetRequests = new HashSet<AssetRequests>();
            CarRequestBudget = new HashSet<CarRequestBudget>();
            CarRequests = new HashSet<CarRequests>();
            MeetingRequestAccountabilityFlow = new HashSet<MeetingRequestAccountabilityFlow>();
            MeetingRequestFlow = new HashSet<MeetingRequestFlow>();
            OrderReload = new HashSet<OrderReload>();
            OrderReloadAccountability = new HashSet<OrderReloadAccountability>();
            OrderRequest = new HashSet<OrderRequest>();
            OrderRequestAccountability = new HashSet<OrderRequestAccountability>();
            RepairItemRequests = new HashSet<RepairItemRequests>();
            RequestActionHistory = new HashSet<RequestActionHistory>();
            RequestFlowUrl = new HashSet<RequestFlowUrl>();
            Requestaction = new HashSet<Requestaction>();
            Requestdata = new HashSet<Requestdata>();
            Requestnote = new HashSet<Requestnote>();
            Requeststakeholder = new HashSet<Requeststakeholder>();
            TravelRequest = new HashSet<TravelRequest>();
        }

        public int Requestid { get; set; }
        public DateTime? Daterequest { get; set; }
        public string Title { get; set; }
        public string Userid { get; set; }
        public string Username { get; set; }
        public int Currentstateid { get; set; }
        public int Processid { get; set; }
        public string Projectid { get; set; }
        public string Note { get; set; }
        public string Url { get; set; }

        public virtual State Currentstate { get; set; }
        public virtual Process Process { get; set; }
        public virtual ICollection<AssetBorrow> AssetBorrow { get; set; }
        public virtual ICollection<AssetRequests> AssetRequests { get; set; }
        public virtual ICollection<CarRequestBudget> CarRequestBudget { get; set; }
        public virtual ICollection<CarRequests> CarRequests { get; set; }
        public virtual ICollection<MeetingRequestAccountabilityFlow> MeetingRequestAccountabilityFlow { get; set; }
        public virtual ICollection<MeetingRequestFlow> MeetingRequestFlow { get; set; }
        public virtual ICollection<OrderReload> OrderReload { get; set; }
        public virtual ICollection<OrderReloadAccountability> OrderReloadAccountability { get; set; }
        public virtual ICollection<OrderRequest> OrderRequest { get; set; }
        public virtual ICollection<OrderRequestAccountability> OrderRequestAccountability { get; set; }
        public virtual ICollection<RepairItemRequests> RepairItemRequests { get; set; }
        public virtual ICollection<RequestActionHistory> RequestActionHistory { get; set; }
        public virtual ICollection<RequestFlowUrl> RequestFlowUrl { get; set; }
        public virtual ICollection<Requestaction> Requestaction { get; set; }
        public virtual ICollection<Requestdata> Requestdata { get; set; }
        public virtual ICollection<Requestnote> Requestnote { get; set; }
        public virtual ICollection<Requeststakeholder> Requeststakeholder { get; set; }
        public virtual ICollection<TravelRequest> TravelRequest { get; set; }
    }
}