// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Requestaction
    {
        public Requestaction()
        {
            RequestActionHistory = new HashSet<RequestActionHistory>();
        }

        public int Requestactionid { get; set; }
        public int Actionid { get; set; }
        public bool Isactive { get; set; }
        public bool Iscomplete { get; set; }
        public int Requestid { get; set; }
        public int Transitionid { get; set; }
        public int? Userid { get; set; }

        public virtual Actions Action { get; set; }
        public virtual RequestFlow Request { get; set; }
        public virtual Transition Transition { get; set; }
        public virtual Users User { get; set; }
        public virtual ICollection<RequestActionHistory> RequestActionHistory { get; set; }
    }
}