// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class State
    {
        public State()
        {
            RequestFlow = new HashSet<RequestFlow>();
            TransitionCurrentstate = new HashSet<Transition>();
            TransitionNextstate = new HashSet<Transition>();
        }

        public int Stateid { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int? Processid { get; set; }
        public int? Statetypeid { get; set; }
        public string Projectid { get; set; }

        public virtual Process Process { get; set; }
        public virtual Statetype Statetype { get; set; }
        public virtual ICollection<RequestFlow> RequestFlow { get; set; }
        public virtual ICollection<Transition> TransitionCurrentstate { get; set; }
        public virtual ICollection<Transition> TransitionNextstate { get; set; }
    }
}