// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Status
    {
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public string Description { get; set; }
    }
}