// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Statetype
    {
        public Statetype()
        {
            State = new HashSet<State>();
        }

        public int Statetypeid { get; set; }
        public string Name { get; set; }
        public string Projectid { get; set; }

        public virtual ICollection<State> State { get; set; }
    }
}