// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Stocks
    {
        public Stocks()
        {
            StockTransaction = new HashSet<StockTransaction>();
        }

        public int Id { get; set; }
        public int OfficeLocationId { get; set; }
        public int OrderItemId { get; set; }

        public virtual OfficeLocations OfficeLocation { get; set; }
        public virtual OrderItem OrderItem { get; set; }
        public virtual ICollection<StockTransaction> StockTransaction { get; set; }
    }
}