// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class StockTransactionStatus
    {
        public StockTransactionStatus()
        {
            StockTransaction = new HashSet<StockTransaction>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? Nominal { get; set; }

        public virtual ICollection<StockTransaction> StockTransaction { get; set; }
    }
}