// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Target
    {
        public Target()
        {
            Actiontarget = new HashSet<Actiontarget>();
            Activitytarget = new HashSet<Activitytarget>();
            TargetUser = new HashSet<TargetUser>();
        }

        public int Targetid { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string Projectid { get; set; }

        public virtual ICollection<Actiontarget> Actiontarget { get; set; }
        public virtual ICollection<Activitytarget> Activitytarget { get; set; }
        public virtual ICollection<TargetUser> TargetUser { get; set; }
    }
}