// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Transitionaction
    {
        public int Transitionid { get; set; }
        public int Actonid { get; set; }

        public virtual Actions Acton { get; set; }
        public virtual Transition Transition { get; set; }
    }
}