// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Transition
    {
        public Transition()
        {
            Requestaction = new HashSet<Requestaction>();
        }

        public int Transitionid { get; set; }
        public int? Currentstateid { get; set; }
        public int? Nextstateid { get; set; }
        public int Processid { get; set; }
        public string Flowtype { get; set; }
        public string Note { get; set; }
        public string Projectid { get; set; }
        public bool? TransitionEnd { get; set; }

        public virtual State Currentstate { get; set; }
        public virtual State Nextstate { get; set; }
        public virtual Process Process { get; set; }
        public virtual Transitionaction Transitionaction { get; set; }
        public virtual ICollection<Requestaction> Requestaction { get; set; }
    }
}