// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class TravelRequest
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string NoRequest { get; set; }
        public DateTime? TransactionDate { get; set; }
        public int? RequestId { get; set; }
        public int? RequesterId { get; set; }
        public string Title { get; set; }
        public int? OfficeLocationId { get; set; }
        public int? JabatanId { get; set; }
        public int? StatusAnggaranId { get; set; }
        public decimal FundAvailable { get; set; }
        public string NoAccount { get; set; }
        public decimal BudgetLeft { get; set; }
        public int? BudgetId { get; set; }
        public decimal TotalBudget { get; set; }
        public int? DepartmentId { get; set; }

        public virtual Jabatan Jabatan { get; set; }
        public virtual OfficeLocations OfficeLocation { get; set; }
        public virtual RequestFlow Request { get; set; }
        public virtual Users Requester { get; set; }
        public virtual TravelHotelRequests TravelHotelRequests { get; set; }
        public virtual TravelRequestAccountability TravelRequestAccountability { get; set; }
        public virtual TravelTransportationRequests TravelTransportationRequests { get; set; }
    }
}