// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class TravelRequestAccountabilityFiles
    {
        public int TravelRequestAccountabilityFilesId { get; set; }
        public int TravelRequestId { get; set; }
        public string FilePath { get; set; }

        public virtual TravelRequestAccountability TravelRequest { get; set; }
    }
}