// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class TravelHotelRequests
    {
        public int TravelRequestId { get; set; }
        public DateTime CheckinAt { get; set; }
        public DateTime CheckoutAt { get; set; }
        public string FilePath { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int? TravelCityId { get; set; }
        public int? TravelHotelId { get; set; }
        public int? RoomTotal { get; set; }
        public decimal? TotalPrice { get; set; }
        public string Note { get; set; }

        public virtual TravelCities TravelCity { get; set; }
        public virtual TravelHotel TravelHotel { get; set; }
        public virtual TravelRequest TravelRequest { get; set; }
    }
}