// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class TravelTransportationRequestDetails
    {
        public int Id { get; set; }
        public int? TravelTransportatonIdRequestId { get; set; }
        public int? TravelOutbondCategoryId { get; set; }
        public int? TravelTransportationNameId { get; set; }
        public int? FromCity { get; set; }
        public int? ToCity { get; set; }
        public DateTime? DepartDateTime { get; set; }
        public DateTime? ArrivalDateTime { get; set; }
        public string FilePath { get; set; }
        public decimal TotalBudget { get; set; }

        public virtual TravelCities FromCityNavigation { get; set; }
        public virtual TravelCities ToCityNavigation { get; set; }
        public virtual TravelOutbondCategory TravelOutbondCategory { get; set; }
        public virtual TravelTransportationName TravelTransportationName { get; set; }
        public virtual TravelTransportationRequests TravelTransportatonIdRequest { get; set; }
    }
}