// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E.Service.Resource.Data.Models
{
    public partial class Users
    {
        public Users()
        {
            AssetBorrow = new HashSet<AssetBorrow>();
            AssetRequestDetails = new HashSet<AssetRequestDetails>();
            AssetRequests = new HashSet<AssetRequests>();
            BorrowRequestDetails = new HashSet<BorrowRequestDetails>();
            BorrowRequests = new HashSet<BorrowRequests>();
            CarDrivers = new HashSet<CarDrivers>();
            CarRequestBudget = new HashSet<CarRequestBudget>();
            CarRequests = new HashSet<CarRequests>();
            ChangeLog = new HashSet<ChangeLog>();
            MeetingRequestAccountability = new HashSet<MeetingRequestAccountability>();
            MeetingRequests = new HashSet<MeetingRequests>();
            MeetingRooms = new HashSet<MeetingRooms>();
            OrderReload = new HashSet<OrderReload>();
            OrderReloadAccountability = new HashSet<OrderReloadAccountability>();
            OrderRequest = new HashSet<OrderRequest>();
            OrderRequestAccountability = new HashSet<OrderRequestAccountability>();
            RepairItemRequestAccountablity = new HashSet<RepairItemRequestAccountablity>();
            RepairItemRequests = new HashSet<RepairItemRequests>();
            RequestActionHistory = new HashSet<RequestActionHistory>();
            Requestaction = new HashSet<Requestaction>();
            TravelRequest = new HashSet<TravelRequest>();
            TravelRequestAccountability = new HashSet<TravelRequestAccountability>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? DepartmentId { get; set; }
        public DateTime? DeletedAt { get; set; }
        public string UserId { get; set; }
        public int? JabatanId { get; set; }
        public int? LocationId { get; set; }
        public bool Active { get; set; }
        public string DeviceId { get; set; }

        public virtual Jabatan Jabatan { get; set; }
        public virtual OfficeLocations Location { get; set; }
        public virtual AspNetUsers User { get; set; }
        public virtual ICollection<AssetBorrow> AssetBorrow { get; set; }
        public virtual ICollection<AssetRequestDetails> AssetRequestDetails { get; set; }
        public virtual ICollection<AssetRequests> AssetRequests { get; set; }
        public virtual ICollection<BorrowRequestDetails> BorrowRequestDetails { get; set; }
        public virtual ICollection<BorrowRequests> BorrowRequests { get; set; }
        public virtual ICollection<CarDrivers> CarDrivers { get; set; }
        public virtual ICollection<CarRequestBudget> CarRequestBudget { get; set; }
        public virtual ICollection<CarRequests> CarRequests { get; set; }
        public virtual ICollection<ChangeLog> ChangeLog { get; set; }
        public virtual ICollection<MeetingRequestAccountability> MeetingRequestAccountability { get; set; }
        public virtual ICollection<MeetingRequests> MeetingRequests { get; set; }
        public virtual ICollection<MeetingRooms> MeetingRooms { get; set; }
        public virtual ICollection<OrderReload> OrderReload { get; set; }
        public virtual ICollection<OrderReloadAccountability> OrderReloadAccountability { get; set; }
        public virtual ICollection<OrderRequest> OrderRequest { get; set; }
        public virtual ICollection<OrderRequestAccountability> OrderRequestAccountability { get; set; }
        public virtual ICollection<RepairItemRequestAccountablity> RepairItemRequestAccountablity { get; set; }
        public virtual ICollection<RepairItemRequests> RepairItemRequests { get; set; }
        public virtual ICollection<RequestActionHistory> RequestActionHistory { get; set; }
        public virtual ICollection<Requestaction> Requestaction { get; set; }
        public virtual ICollection<TravelRequest> TravelRequest { get; set; }
        public virtual ICollection<TravelRequestAccountability> TravelRequestAccountability { get; set; }
    }
}